Add test.py check to CI

diff --git a/.github/workflows/on_push.yml b/.github/workflows/on_push.yml
--- a/.github/workflows/on_push.yml
+++ b/.github/workflows/on_push.yml
@@ -48,6 +48,15 @@ jobs:
           uv sync --all-extras --dev
       - name: Run pre-commit
         run: uvx pre-commit run --all-files
+      - name: Check types in test.py
+        run: |
+          uv build --wheel
+          OUTPUT=`uvx --python=3.8 --with dist/*.whl mypy test.py || true`
+          echo $OUTPUT
+          if [[ ${OUTPUT} != *"Found 1 error"* ]];then
+            echo "Stubs test failed: $TEST"
+            exit 1
+          fi
       - name: Stubs consistency check
         if: ${{ matrix.check-consistency }}
         run: |
